jubilee:
  userName: 'wanghan52@126.com'
  cookieDir: '/Users/gilbert/jubilee/'
  initUrl: 'https://jubilee.ae/collections/women'
  category: 'women'
  totalPages: 25
  begin: 16
  db:
    host: 192.168.8.12
    port: 13306
    user: root
    pass: KPqazxsw
    dbName: kp_sk_sync
